/*
 * Locationforecast_2_0
 * Weather forecast for a specified place
 *
 * OpenAPI spec version: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corvettecole.pixelwatchface.api.met.models;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * ForecastTimeStep
 */
public class ForecastTimeStep {

  @SerializedName("data")
  private ForecastTimeStepData data = null;

  @SerializedName("time")
  private String time = null;

  public ForecastTimeStep data(ForecastTimeStepData data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   *
   * @return data
   **/
  public ForecastTimeStepData getData() {
    return data;
  }

  public void setData(ForecastTimeStepData data) {
    this.data = data;
  }

  public ForecastTimeStep time(String time) {
    this.time = time;
    return this;
  }

  /**
   * The time these forecast values are valid for. Timestamp in format YYYY-MM-DDThh:mm:ssZ (ISO
   * 8601)
   *
   * @return time
   **/
  public String getTime() {
    return time;
  }

  public void setTime(String time) {
    this.time = time;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStep forecastTimeStep = (ForecastTimeStep) o;
    return Objects.equals(this.data, forecastTimeStep.data) &&
        Objects.equals(this.time, forecastTimeStep.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, time);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStep {\n");

    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

