/*
 * Locationforecast_2_0
 * Weather forecast for a specified place
 *
 * OpenAPI spec version: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corvettecole.pixelwatchface.api.met.models;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * Parameters with validity times over one hour. Will not exist for all time steps.
 */
public class ForecastTimeStepDataNext1Hours {

  @SerializedName("details")
  private ForecastTimePeriod details = null;

  @SerializedName("summary")
  private ForecastSummary summary = null;

  public ForecastTimeStepDataNext1Hours details(ForecastTimePeriod details) {
    this.details = details;
    return this;
  }

  /**
   * Get details
   *
   * @return details
   **/
  public ForecastTimePeriod getDetails() {
    return details;
  }

  public void setDetails(ForecastTimePeriod details) {
    this.details = details;
  }

  public ForecastTimeStepDataNext1Hours summary(ForecastSummary summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   *
   * @return summary
   **/
  public ForecastSummary getSummary() {
    return summary;
  }

  public void setSummary(ForecastSummary summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStepDataNext1Hours forecastTimeStepDataNext1Hours = (ForecastTimeStepDataNext1Hours) o;
    return Objects.equals(this.details, forecastTimeStepDataNext1Hours.details) &&
        Objects.equals(this.summary, forecastTimeStepDataNext1Hours.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, summary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStepDataNext1Hours {\n");

    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

