/*
 * Locationforecast_2_0
 * Weather forecast for a specified place
 *
 * OpenAPI spec version: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corvettecole.pixelwatchface.api.met.models;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;


/**
 * ForecastMeta
 */
public class ForecastMeta {

  @SerializedName("updated_at")
  private String updatedAt = null;

  @SerializedName("units")
  private ForecastUnits units = null;

  public ForecastMeta updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Update time for this forecast
   *
   * @return updatedAt
   **/
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ForecastMeta units(ForecastUnits units) {
    this.units = units;
    return this;
  }

  /**
   * Get units
   *
   * @return units
   **/
  public ForecastUnits getUnits() {
    return units;
  }

  public void setUnits(ForecastUnits units) {
    this.units = units;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastMeta forecastMeta = (ForecastMeta) o;
    return Objects.equals(this.updatedAt, forecastMeta.updatedAt) &&
        Objects.equals(this.units, forecastMeta.units);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updatedAt, units);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastMeta {\n");

    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

