/*
 * Locationforecast_2_0
 * Weather forecast for a specified place
 *
 * OpenAPI spec version: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corvettecole.pixelwatchface.api.met.models;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * Forecast for a specific time
 */
public class ForecastTimeStepData {

  @SerializedName("next_6_hours")
  private ForecastTimeStepDataNext6Hours next6Hours = null;

  @SerializedName("next_1_hours")
  private ForecastTimeStepDataNext1Hours next1Hours = null;

  @SerializedName("instant")
  private ForecastTimeStepDataInstant instant = null;

  public ForecastTimeStepData next6Hours(ForecastTimeStepDataNext6Hours next6Hours) {
    this.next6Hours = next6Hours;
    return this;
  }

  /**
   * Get next6Hours
   *
   * @return next6Hours
   **/
  public ForecastTimeStepDataNext6Hours getNext6Hours() {
    return next6Hours;
  }

  public void setNext6Hours(ForecastTimeStepDataNext6Hours next6Hours) {
    this.next6Hours = next6Hours;
  }

  public ForecastTimeStepData next1Hours(ForecastTimeStepDataNext1Hours next1Hours) {
    this.next1Hours = next1Hours;
    return this;
  }

  /**
   * Get next1Hours
   *
   * @return next1Hours
   **/
  public ForecastTimeStepDataNext1Hours getNext1Hours() {
    return next1Hours;
  }

  public void setNext1Hours(ForecastTimeStepDataNext1Hours next1Hours) {
    this.next1Hours = next1Hours;
  }

  public ForecastTimeStepData instant(ForecastTimeStepDataInstant instant) {
    this.instant = instant;
    return this;
  }

  /**
   * Get instant
   *
   * @return instant
   **/
  public ForecastTimeStepDataInstant getInstant() {
    return instant;
  }

  public void setInstant(ForecastTimeStepDataInstant instant) {
    this.instant = instant;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStepData forecastTimeStepData = (ForecastTimeStepData) o;
    return Objects.equals(this.next6Hours, forecastTimeStepData.next6Hours) &&
        Objects.equals(this.next1Hours, forecastTimeStepData.next1Hours) &&
        Objects.equals(this.instant, forecastTimeStepData.instant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(next6Hours, next1Hours, instant);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStepData {\n");

    sb.append("    next6Hours: ").append(toIndentedString(next6Hours)).append("\n");
    sb.append("    next1Hours: ").append(toIndentedString(next1Hours)).append("\n");
    sb.append("    instant: ").append(toIndentedString(instant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

